# Configure main menu and social menu
# [[main]]
# identifier = "home"
# name = "Home"
# url = "/"
# [main.params]
# icon = "home"
# newtab = false

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/zakimal"
[social.params]
icon = "brand-github"

# [[social]]
# identifier = "twitter"
# name = "Twitter"
# url = "https://twitter.com"
# [social.params]
# icon = "brand-twitter"

[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"
[social.params]
icon = "rss"

[[social]]
identifier = "mail"
name = "Mail"
url = "mailto:oza777you@gmail.com"
[social.params]
icon = "mail"
